apiVersion: v2
name: kube-prometheus-stack
type: application
version: 1.0.0
dependencies:
- name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 67.10.0