apiVersion: v1
kind: ConfigMap
metadata:
  name: octoprint-proxy-config
data:
  Caddyfile: |
    :80 {
      basicauth {
        matt JDJhJDE0JGtiLkplZ295YTdJV2pIMzRkYVlTWmVvNmxmbGlaZnNvaC9FWk5ZWjU4MzNCZjgwOEtDOUdt
      }
      reverse_proxy 192.168.68.68:80 {
        trusted_proxies private_ranges
      }
    }